// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw9f_oZFcBLd6VgSpWXW_Z2BDcTyYX-dc',
    appId: '1:546321107813:web:db2ffb1956db192e4eef8c',
    messagingSenderId: '546321107813',
    projectId: 'ai-med-scribble-c6e43',
    authDomain: 'ai-med-scribble-c6e43.firebaseapp.com',
    storageBucket: 'ai-med-scribble-c6e43.appspot.com',
    measurementId: 'G-55YK8VMKEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXGVXe9NJrtOlunZSvdkGzdriCKcEoYP0',
    appId: '1:546321107813:android:8188f28b69e041d04eef8c',
    messagingSenderId: '546321107813',
    projectId: 'ai-med-scribble-c6e43',
    storageBucket: 'ai-med-scribble-c6e43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7xYaa5Ve_7Wfq6rE3yAGW1laYMmqPzbw',
    appId: '1:546321107813:ios:06efa5a848e4b34b4eef8c',
    messagingSenderId: '546321107813',
    projectId: 'ai-med-scribble-c6e43',
    storageBucket: 'ai-med-scribble-c6e43.appspot.com',
    iosClientId: '546321107813-aq1vbnq384pt2q84vl8o0f86f01hapl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.aimedscribble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7xYaa5Ve_7Wfq6rE3yAGW1laYMmqPzbw',
    appId: '1:546321107813:ios:700917bbd4a260f64eef8c',
    messagingSenderId: '546321107813',
    projectId: 'ai-med-scribble-c6e43',
    storageBucket: 'ai-med-scribble-c6e43.appspot.com',
    iosClientId: '546321107813-uqtm6v1lu36mlj5s6642b75o6nraejlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.aimedscribble.RunnerTests',
  );
}
